import type { CategoryIconNames } from './category-icon.type'

export const categoryIconDisplayName: Record<CategoryIconNames, string> = {
  'category-42Seoul': '42Seoul',
  'category-Algorithm': '알고리즘',
  'category-Android': 'Android',
  'category-Apple': 'Apple',
  'category-AppleDeveloperAcademy': 'Apple Developer Academy',
  'category-AppleOS': '',
  'category-Assembly': 'Assembly',
  'category-C': 'C',
  'category-CS': 'Computer Science',
  'category-CSS': 'CSS',
  'category-CSharp': 'C#',
  'category-DeepLearning': '딥러닝',
  'category-Development': '개발 지식',
  'category-Django': 'Django',
  'category-Docker': 'Docker',
  'category-DotNET': '.NET',
  'category-Electron': 'Electron',
  'category-Flutter': 'Flutter',
  'category-GO': 'Go',
  'category-Github': 'Github',
  'category-Google': 'Google',
  'category-Graphics': '그래픽스',
  'category-HTML': 'HTML',
  'category-Haskell': 'Haskell',
  'category-Java': 'Java',
  'category-JavaScript': 'JavaScript',
  'category-Kotlin': 'Kotlin',
  'category-Kubernetes': 'Kubernetes',
  'category-Linux': 'Linux',
  'category-Math': '수학',
  'category-Microsoft': 'Microsoft',
  'category-NGINX': 'NGINX',
  'category-Network': '네트워크',
  'category-NetworkWired': '유선 네트워크',
  'category-NetworkWireless': '무선 네트워크',
  'category-NextJs': 'Next.js',
  'category-Nodejs': 'Node.js',
  'category-Notion': 'Notion',
  'category-OS': '운영체제',
  'category-PHP': 'PHP',
  'category-Python': 'Python',
  'category-React': 'React',
  'category-ReactNative': 'React Native',
  'category-Rust': 'Rust',
  'category-Shell': 'Shell',
  'category-Spring': 'Spring',
  'category-Swift': 'Swift',
  'category-SwiftUI': 'SwiftUI',
  'category-TypeScript': 'TypeScript',
  'category-Ubuntu': 'Ubuntu',
  'category-Unity': 'Unity',
  'category-VScode': 'VS Code',
  'category-Vim': 'Vim',
  'category-Vue': 'Vue.js',
  'category-Web': '웹',
  'category-Windows': 'Windows',
  'category-Xcode': 'Xcode',
  'category-cpp': 'C++',
}

export const categoryIconColor: Record<CategoryIconNames, string> = {
  // #000000
  'category-NextJs': '#000000',
  'category-Github': '#000000',
  'category-42Seoul': '#000000',
  // #292C30
  'category-Assembly': '#292C30',
  'category-HTML': '#292C30',
  'category-Kotlin': '#292C30',
  'category-C': '#292C30',
  'category-cpp': '#292C30',
  'category-CSharp': '#292C30',
  'category-Python': '#292C30',
  'category-CSS': '#292C30',
  'category-React': '#292C30',
  'category-ReactNative': '#292C30',
  'category-Vue': '#292C30',
  'category-VScode': '#292C30',
  'category-Notion': '#292C30',
  // #494949
  'category-Apple': '#494949',
  'category-AppleOS': '#494949',
  'category-Haskell': '#494949',
  // #FAFAFF
  'category-Network': '#FAFAFF',
  'category-NetworkWired': '#FAFAFF',
  'category-NetworkWireless': '#FAFAFF',
  'category-Web': '#FAFAFF',
  'category-CS': '#FAFAFF',
  'category-OS': '#FAFAFF',
  'category-DeepLearning': '#FAFAFF',
  'category-Algorithm': '#FAFAFF',
  'category-Graphics': '#FAFAFF',
  'category-Math': '#FAFAFF',
  'category-Development': '#FAFAFF',
  'category-Linux': '#FAFAFF',
  'category-Microsoft': '#FAFAFF',
  'category-Google': '#FAFAFF',
  // #C9005F
  'category-AppleDeveloperAcademy': '#C9005F',
  // #F05239
  'category-Swift': '#F05239',
  'category-Java': '#F05239',
  // #F47421
  'category-Ubuntu': '#F47421',
  'category-Rust': '#F47421',
  // #F7DF1E
  'category-JavaScript': '#F7DF1E',
  // #77BC1F
  'category-Nodejs': '#77BC1F',
  'category-Spring': '#77BC1F',
  // #019639
  'category-NGINX': '#019639',
  'category-Vim': '#019639',
  // #2BA977
  'category-Android': '#2BA977',
  'category-Django': '#2BA977',
  // #08A6ED
  'category-Xcode': '#08A6ED',
  'category-Windows': '#08A6ED',
  'category-Flutter': '#08A6ED',
  // #2396ED
  'category-DotNET': '#2396ED',
  'category-Docker': '#2396ED',
  'category-TypeScript': '#2396ED',
  'category-GO': '#2396ED',
  // #326CE5
  'category-SwiftUI': '#326CE5',
  'category-Kubernetes': '#326CE5',
  // #3E5781
  'category-PHP': '#3E5781',
  // #353C4B
  'category-Electron': '#353C4B',
  'category-Unity': '#353C4B',
  'category-Shell': '#353C4B',
}
