import type { CategoryIconNamesWithoutRounded } from './CategoryIcons.type'

export const categoryIconDisplayName: Record<CategoryIconNamesWithoutRounded, string> = {
  '42Seoul': '42Seoul',
  All: 'All',
  Algorithm: '알고리즘',
  Android: 'Android',
  Apple: 'Apple',
  AppleDeveloperAcademy: 'Apple Developer Academy',
  AppleOS: 'AppleOS',
  Assembly: 'Assembly',
  C: 'C',
  CS: 'Computer Science',
  CSS: 'CSS',
  Cpp: 'C++',
  CSharp: 'C#',
  DeepLearning: '딥러닝',
  Development: '개발 지식',
  Django: 'Django',
  Docker: 'Docker',
  DotNET: '.NET',
  Electron: 'Electron',
  Flutter: 'Flutter',
  GO: 'Go',
  Github: 'Github',
  Google: 'Google',
  Graphics: '그래픽스',
  HTML: 'HTML',
  Haskell: 'Haskell',
  Java: 'Java',
  JavaScript: 'JavaScript',
  Kotlin: 'Kotlin',
  Kubernetes: 'Kubernetes',
  Linux: 'Linux',
  Math: '수학',
  Microsoft: 'Microsoft',
  NGINX: 'NGINX',
  Network: '네트워크',
  NetworkWired: '유선 네트워크',
  NetworkWireless: '무선 네트워크',
  NextJs: 'Next.js',
  Nodejs: 'Node.js',
  Notion: 'Notion',
  OS: '운영체제',
  PHP: 'PHP',
  Python: 'Python',
  React: 'React',
  ReactNative: 'React Native',
  Rust: 'Rust',
  Shell: 'Shell',
  Spring: 'Spring',
  Swift: 'Swift',
  SwiftUI: 'SwiftUI',
  TypeScript: 'TypeScript',
  Ubuntu: 'Ubuntu',
  Unity: 'Unity',
  VScode: 'VS Code',
  Vim: 'Vim',
  Vue: 'Vue.js',
  Web: '웹',
  Windows: 'Windows',
  Xcode: 'Xcode',
}
export type categoryIconColor = {
  [key in CategoryIconNamesWithoutRounded]: {
    bg: string
    fg: string
  }
}
export const categoryIconColor: categoryIconColor = {
  // #000000
  NextJs: { bg: '#000000', fg: '#ffffff' },
  Github: { bg: '#000000', fg: '#ffffff' },
  '42Seoul': { bg: '#000000', fg: '#ffffff' },
  // #292C30
  Assembly: { bg: '#292C30', fg: '#ffffff' },
  HTML: { bg: '#292C30', fg: '#ffffff' },
  Kotlin: { bg: '#292C30', fg: '#ffffff' },
  C: { bg: '#292C30', fg: '#ffffff' },
  Cpp: { bg: '#292C30', fg: '#ffffff' },
  CSharp: { bg: '#292C30', fg: '#ffffff' },
  Python: { bg: '#292C30', fg: '#ffffff' },
  CSS: { bg: '#292C30', fg: '#ffffff' },
  React: { bg: '#292C30', fg: '#ffffff' },
  ReactNative: { bg: '#292C30', fg: '#ffffff' },
  Vue: { bg: '#292C30', fg: '#ffffff' },
  VScode: { bg: '#292C30', fg: '#ffffff' },
  Notion: { bg: '#292C30', fg: '#ffffff' },
  // #494949
  Apple: { bg: '#494949', fg: '#ffffff' },
  AppleOS: { bg: '#494949', fg: '#ffffff' },
  Haskell: { bg: '#494949', fg: '#ffffff' },
  // #FAFAFF
  All: { bg: '#FAFAFF', fg: '#000000' },
  Network: { bg: '#FAFAFF', fg: '#000000' },
  NetworkWired: { bg: '#FAFAFF', fg: '#000000' },
  NetworkWireless: { bg: '#FAFAFF', fg: '#000000' },
  Web: { bg: '#FAFAFF', fg: '#000000' },
  CS: { bg: '#FAFAFF', fg: '#000000' },
  OS: { bg: '#FAFAFF', fg: '#000000' },
  DeepLearning: { bg: '#FAFAFF', fg: '#000000' },
  Algorithm: { bg: '#FAFAFF', fg: '#000000' },
  Graphics: { bg: '#FAFAFF', fg: '#000000' },
  Math: { bg: '#FAFAFF', fg: '#000000' },
  Development: { bg: '#FAFAFF', fg: '#000000' },
  Linux: { bg: '#FAFAFF', fg: '#000000' },
  Microsoft: { bg: '#FAFAFF', fg: '#000000' },
  Google: { bg: '#FAFAFF', fg: '#000000' },
  // #C9005F
  AppleDeveloperAcademy: { bg: '#C9005F', fg: '#ffffff' },
  // #F05239
  Swift: { bg: '#F05239', fg: '#ffffff' },
  Java: { bg: '#F05239', fg: '#ffffff' },
  // #F47421
  Ubuntu: { bg: '#F47421', fg: '#ffffff' },
  Rust: { bg: '#F47421', fg: '#ffffff' },
  // #F7DF1E
  JavaScript: { bg: '#F7DF1E', fg: '#000000' },
  // #77BC1F
  Nodejs: { bg: '#77BC1F', fg: '#ffffff' },
  Spring: { bg: '#77BC1F', fg: '#ffffff' },
  // #019639
  NGINX: { bg: '#019639', fg: '#ffffff' },
  Vim: { bg: '#019639', fg: '#ffffff' },
  // #2BA977
  Android: { bg: '#2BA977', fg: '#ffffff' },
  Django: { bg: '#2BA977', fg: '#ffffff' },
  // #08A6ED
  Xcode: { bg: '#08A6ED', fg: '#ffffff' },
  Windows: { bg: '#08A6ED', fg: '#ffffff' },
  Flutter: { bg: '#08A6ED', fg: '#ffffff' },
  // #2396ED
  DotNET: { bg: '#2396ED', fg: '#ffffff' },
  Docker: { bg: '#2396ED', fg: '#ffffff' },
  TypeScript: { bg: '#2396ED', fg: '#ffffff' },
  GO: { bg: '#2396ED', fg: '#ffffff' },
  // #326CE5
  SwiftUI: { bg: '#326CE5', fg: '#ffffff' },
  Kubernetes: { bg: '#326CE5', fg: '#ffffff' },
  // #3E5781
  PHP: { bg: '#3E5781', fg: '#ffffff' },
  // #353C4B
  Electron: { bg: '#353C4B', fg: '#ffffff' },
  Unity: { bg: '#353C4B', fg: '#ffffff' },
  Shell: { bg: '#353C4B', fg: '#ffffff' },
}
